/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class binbin_leslie_cn_mylibrary_NdkString */

#ifndef _Included_binbin_leslie_cn_mylibrary_NdkString
#define _Included_binbin_leslie_cn_mylibrary_NdkString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     binbin_leslie_cn_mylibrary_NdkString
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_binbin_leslie_cn_mylibrary_NdkString_getStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
