/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class binbin_leslie_cn_mylibrary_LeslieJni */

#ifndef _Included_binbin_leslie_cn_mylibrary_LeslieJni
#define _Included_binbin_leslie_cn_mylibrary_LeslieJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     binbin_leslie_cn_mylibrary_LeslieJni
 * Method:    getStringFromLesJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_binbin_leslie_cn_mylibrary_LeslieJni_getStringFromLesJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
